Adapted.

diff --git a/vm-seam/bin/alicerun b/vm-seam/bin/alicerun
--- a/vm-seam/bin/alicerun
+++ b/vm-seam/bin/alicerun
@@ -2,6 +2,8 @@
 
 set -e
 
+cmd="$0"
+
 find_in () {
     search_for=$1
     found_in=""
@@ -12,11 +14,22 @@ find_in () {
 	fi
     done
     if test -z "${found_in}"; then
-	echo "Error: Could not find ${search_for} in either of" >&2
+	echo "$cmd: error: could not find ${search_for} in either of" >&2
 	for d in "$@"; do echo "  $d" >&2; done
 	exit 1
     fi
     echo "${found_in}"
+}
+
+abs_path () {
+    case "$1" in
+	/*)
+	    echo "$1"
+	    ;;
+	*)
+	    echo "$(pwd)/$1"
+	    ;;
+    esac
 }
 
 if test -z "${ALICE_HOME}"; then
@@ -24,6 +37,13 @@ if test -z "${ALICE_HOME}"; then
     dir=$(dirname "$dir")
     ALICE_HOME=$(find_in alice.dll /usr/share/alice "$PROGRAMFILES/Alice" "$dir")
 fi
+ALICE_HOME=$(abs_path "$ALICE_HOME")
+
+if test -z "${SEAM_HOME}"; then
+    SEAM_HOME=$(find_in seam.exe "$PROGRAMFILES/Seam/bin")
+    SEAM_HOME=$(dirname "$SEAM_HOME")
+fi
+SEAM_HOME=$(abs_path "$SEAM_HOME")
 
 case $(uname) in
     CYGWIN*)
@@ -33,9 +53,9 @@ case $(uname) in
     *)
 	if [ -z "$LD_LIBRARY_PATH" ]
 	then
-	    LD_LIBRARY_PATH=$ALICE_HOME
+	    LD_LIBRARY_PATH=$SEAM_HOME/bin:$ALICE_HOME
 	else
-	    LD_LIBRARY_PATH=$ALICE_HOME:$LD_LIBRARY_PATH
+	    LD_LIBRARY_PATH=$SEAM_HOME/bin:$ALICE_HOME:$LD_LIBRARY_PATH
 	fi
 	export LD_LIBRARY_PATH
 	sep=:
@@ -57,10 +77,10 @@ export ALICE_HOME ALICE_LOAD
 
 ## To use the GUI debugger on Windows/Cygwin:
 #echo run alice "$@"
-#exec insight "$ALICE_HOME"/seam.exe
+#exec insight "$SEAM_HOME"/seam.exe
 
 ## To use the debugger on Unix:
 #(echo "break Base.cc:22"; echo "tty /dev/pts/4"; echo run alice "$@"; cat) |
-#exec gdb "$ALICE_HOME"/seam.exe
+#exec gdb "$SEAM_HOME"/seam.exe
 
-exec "$ALICE_HOME"/seam.exe alice "$@"
+exec "$SEAM_HOME"/bin/seam.exe alice "$@"
