* files are now (hopefully) Win32 compatible * BUILD_ALL now checks PKG_CONFIG_PATH;   invoke with 'BUILD_ALL --windows' to build for windows

diff --git a/lib/gtk/seam/BUILD_ALL b/lib/gtk/seam/BUILD_ALL
--- a/lib/gtk/seam/BUILD_ALL
+++ b/lib/gtk/seam/BUILD_ALL
@@ -1,2 +1,17 @@
 #!/bin/sh
-(make generate && make depend && make compile docs)
+if ! pkg-config gtk+-2.0 libgnomecanvas-2.0 >& /dev/null ; then
+  echo "** 'pkg-config gtk+-2.0 libgnomecanvas-2.0' failed!"
+  echo "** Either GTK+ and GnomeCanvas are not installed,"
+  echo "** or the PKG_CONFIG_PATH variable is not set to the"
+  echo "** appropriate ..../lib/pkgconfig path."
+  exit 1 ;
+fi
+
+if test x$1 = "x--windows" ; then
+  WINDOWS=1 ;
+fi
+
+(make generate WINDOWS=$WINDOWS && 
+ make depend   WINDOWS=$WINDOWS && 
+ make compile  WINDOWS=$WINDOWS)
+
